name = "simple_pubsub"
version = "0.1.0"
description = "Simple pubsub (publish-subscribe) system for gleam based on process groups"
licences = ["Apache-2.0"]
repository = { type = "github", user = "RudolfVonKrugstein", repo = "gleam_simple_pubsub" }
links = [{ title = "gleam", href = "https://gleam.run" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
processgroups = ">= 0.1.3 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_otp = ">= 0.10.0 and < 1.0.0"
